#version 450

layout(push_constant) uniform upc {
  uint jump;
  uint div;
} pc;

layout(binding = 0) buffer buf_0 { uint inp[]; };

void main() {
  uint id = gl_GlobalInvocationID.x;

  uint dv = id / pc.div;
  uint rs = id % pc.div;

  uint ra = rs;
  uint rb = (rs + pc.div / 2) % pc.div;

  uint ia = dv * pc.div + ra;
  uint ib = dv * pc.div + rb;
  if (ib < ia) return;

  uint a = inp[ia];
  uint b = inp[ib];
  if (((id / pc.jump) % 2 == 1) ^^ (ia < ib)) {
    inp[ia] = min(a, b);
    inp[ib] = max(a, b);
  } else {
    inp[ia] = max(a, b);
    inp[ib] = min(a, b);
  }
}
