#version 450

layout(push_constant) uniform upc {
  uint jump;
  uint div;
} pc;

layout(binding = 0) readonly buffer buf_0 { uint inp[]; };
layout(binding = 1) buffer buf_1 { uint res[]; };

void main() {
  uint ia = gl_GlobalInvocationID.x;
  uint ib = ia + pc.jump;

  uint a = inp[ia];
  uint b = inp[ib];
  if ((ia / pc.div) % 2 == 0) {
    res[ia] = min(a, b);
    res[ib] = max(a, b);
  } else {
    res[ia] = max(a, b);
    res[ib] = min(a, b);
  }
}
