name: Install glslang
runs:
  using: composite
  steps:
    - name: Install via download
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile glslang.zip -Uri https://github.com/m4c0/glslangValidator/releases/download/v0/glslang-windows.zip
        Expand-Archive glslang.zip -DestinationPath glslang
        $Bin = Get-Item .\glslang\bin
        Add-Content -Path $env:GITHUB_PATH -Value $Bin.FullName
    - name: Install via homebrew
      if: runner.os == 'macOS'
      shell: bash
      run: brew install glslang
    - name: Install via linuxbrew
      if: runner.os == 'Linux'
      shell: bash
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install glslang

