name: Prepare Deps
runs:
  using: composite
  steps:
    - uses: m4c0/casein/.github/actions/deps@main
    - uses: m4c0/hai/.github/actions/deps@main
    - uses: m4c0/jute/.github/actions/deps@main
    - uses: m4c0/silog/.github/actions/deps@main
    - uses: m4c0/traits/.github/actions/deps@main
    - uses: actions/checkout@v3
      with:
        repository: m4c0/vee
        path: vee
        submodules: true
