name: Prepare Deps
runs:
  using: composite
  steps:
    - uses: m4c0/casein/.github/actions/deps@main
    - uses: m4c0/hai/.github/actions/deps@main
    - uses: m4c0/jute/.github/actions/deps@main
    - uses: m4c0/silog/.github/actions/deps@main
    - uses: m4c0/sires/.github/actions/deps@main
    - uses: m4c0/traits/.github/actions/deps@main
    - uses: m4c0/ecow/.github/actions/checkout@main
      id: vee
      with:
        path: vee
    - uses: m4c0/molten-vk-build/.github/actions/setup@main
      if: steps.vee.outputs.cache-hit != 'true'
      with:
        cwd: vee
