name: build module
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🧰 Setup
        uses: m4c0/leco/.github/actions/setup@main
      - name: 🧀 Prepare Deps
        uses: m4c0/vee/.github/actions/deps@main
      - name: 🖖 Install glslang
        uses: m4c0/vee/.github/actions/glslang@main
      - name: 🔨 Build
        run: ./leco/leco.exe -C vee

